---
title: Getting Started with the Climate Adaptation Data Platform
author: Brian Lee Yung Rowe
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["book.bib"]
biblio-style: apalike
link-citations: yes
header-includes: |
    \usepackage{tikz}
    \usepackage{pgfplots}
---

```{r, echo=FALSE}
library(knitr)
```

# Preface

We are witnessing the effects of climate change quickly accelerate.
The consequences of these changes are just starting to be felt.
To avoid widespread suffering, we need to similarly accelerate climate
adaptation initiatives.

The [Climate Adaptation Data Platform (CADP)](https://github.com/zatonovo/zeomancer_system) aims to do just that.
By bringing together multiple stakeholders,
we can solve multiple climate-related challenges concurrently.
This drives down costs and increases reach.

Consistent with the above goal, 
the [CADP is an open source project](https://github.com/zatonovo/zeomancer_system).
This guide details how to use and develop the CADP. 
Those wishing to contribute to the CADP should read this guide first.
Those who only want to use the CADP can skip most of the theory and focus
on the latter half of the book.


## License
Copyright (C) 2024 Zato Novo, LLC.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
